name: seisnote
channels:
    - conda-forge
    - defaults
dependencies:
    - python==3.8
    - pip
    # obspy numpy pandas xarray netcdf4 packaging gmt
    - obspy
    - cartopy
    # pygmt
    - numpy
    - pandas
    - xarray
    - netCDF4
    - packaging
    - black
    - blackdoc
    - coverage[toml]
    - docformatter
    - flake8
    - ipython
    - isort>=5
    - jupyter
    - matplotlib
    - nbsphinx
    - pylint
    - pytest-cov
    - pytest-mpl
    - pytest>=6.0
    - ipython
    - gmt
    - pygmt
    # sphinx
    - sphinx
    - sphinx-gallery
    - sphinx_rtd_theme
    - sphinx-tabs
    - pip:
      - sphinx-cjkspace