name: seisnote
channels:
    - conda-forge
    - defaults
dependencies:
    - python==3.8
    - pip
    # obspy numpy pandas xarray netcdf4 packaging gmt
    - obspy
    - cartopy
    # pygmt
    - ipython
    - numpy
    - pandas
    - xarray
    - netcdf4
    - packaging
    - gmt
    - pygmt
    # sphinx
    - sphinx
    - sphinx-gallery
    - sphinx_rtd_theme
    - sphinx-tabs
    - pip:
      - sphinx-cjkspace