name: seisnote
channels:
    - conda-forge
    - defaults
dependencies:
    - python==3.8
    - pip
    # obspy 
    - obspy
    - cartopy
    # pygmt
    - numpy
    - pandas
    - xarray
    - netCDF4
    - packaging
    - ipython
    - gmt
    - pygmt
    # sphinx
    - sphinx
    - sphinx-gallery
    - sphinx_rtd_theme
    - sphinx-tabs
    - sphinx_copybutton
    - pip:
      - sphinx-cjkspace