name: seisnote
channels:
    - conda-forge
    - defaults
# sphinx-cjkspace 只能用 pip 下载，此environment停用
    dependencies:
    - python=3.8
    - pip
    - sphinx
    - sphinx-gallery
    - sphinx_rtd_theme
    - sphinx-tabs