name: seisnote
channels:
    - conda-forge
    - defaults
dependencies:
    - python==3.8
    - pip
    - obspy
    - sphinx
    - sphinx-gallery
    - sphinx_rtd_theme
    - sphinx-tabs
    - cartopy
    - pip:
      - sphinx-cjkspace